// 파일 위치: apps/frontend/src/app/layout.tsx (v1.3 - async/await 적용)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from 'next/headers';
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deep Dive!",
  description: "Generated by LEEJUNGYU",
};

const setInitialTheme = `
  (function() {
    // ... (FOUC 방지 스크립트 내용은 변경 없음)
  })();
`;

// --- [핵심 수정 1] RootLayout을 'async' 함수로 변경합니다. ---
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // --- [핵심 수정 2] cookies() 호출 시 'await'를 추가합니다. ---
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value || 'light';

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      {/* --- body에 배경색과 텍스트색을 적용합니다. --- */}
      <body className={`${inter.className} bg-background text-foreground transition-colors duration-300`}>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />

        <div className="flex flex-col min-h-screen">
          <Providers>
            <Header />
            <main className="flex-grow max-w-7xl mx-auto px-6 py-8 w-full">
              {children}
            </main>
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}