// apps/frontend/src/app/layout.tsx (임시 수정본)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Providers from "./providers"; // 1. Providers import 구문 주석 처리 또는 삭제

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Providers>{children}</Providers> */} {/* 2. Providers로 감싸던 부분 제거 */}
        {children} {/* 3. children을 직접 렌더링 */}
      </body>
    </html>
  );
}