# .github/workflows/backend-ci.yml
name: Backend CI (Build & Upload Lambda Artifact)

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-northeast-2
      ARTIFACT_BUCKET_NAME_BASE: blog-lambda-artifacts-${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # v3 또는 v4 사용 가능. v3도 충분히 최신입니다.
        with:
          version: 9 # ⭐ 로컬 pnpm 버전과 동일하게 명시. (pnpm --version으로 확인)
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsCDKDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Backend Lambda
        run: pnpm --filter backend build
        working-directory: ./apps/backend

      - name: Zip Lambda Artifact
        run: zip -r backend.zip dist node_modules
        working-directory: ./apps/backend

      - name: Upload Lambda Artifact to S3
        run: aws s3 cp backend.zip s3://${{ env.ARTIFACT_BUCKET_NAME_BASE }}-${{ env.AWS_REGION }}/backend/${{ github.sha }}.zip
        working-directory: ./apps/backend

      - name: Clean up
        run: rm backend.zip
        working-directory: ./apps/backend