# 파일 위치: .github/workflows/deploy-infra.yml
# 역할: 오직 인프라 변경사항만을 '수동으로' 신속하게 배포하는 워크플로우

name: "Manual Deploy Infrastructure"

on:
  workflow_dispatch: # [핵심] 수동 실행을 가능하게 합니다.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js & pnpm"
        uses: pnpm/action-setup@v4
        with:

          run_install: |
            - recursive: true
              args: [--frozen-lockfile]


      - name: "Build Frontend for S3 Assets"
        run: pnpm --filter frontend run build

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Deploy to AWS via CDK"
        run: |
          pnpm --filter infra exec cdk deploy --all \
            --require-approval never \
            --parameters ImageTag=infra-only-deploy