# 파일 위치: .github/workflows/deploy-cicd-infra.yml
# 최종 버전: v2025.08.08-Republic-of-CICD
# 역할: Self-Hosted Runner 인프라(CiCdStack)만을 배포하고 관리한다.

name: "Deploy CI/CD Support Infrastructure"

on:
  # 1. 수동으로 실행할 수 있도록 workflow_dispatch 트리거를 추가합니다.
  workflow_dispatch:

  # 2. CiCdStack 관련 파일이 main 브랜치에 푸시되었을 때만 자동으로 실행됩니다.
  push:
    branches: [main]
    paths:
      - 'apps/infra/lib/cicd-stack.ts'
      - 'apps/infra/bin/infra.ts' # 스택 등록 변경 시에도 실행
      - '.github/workflows/deploy-cicd-infra.yml' # 워크플로우 자체 변경 시에도 실행

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest # 이 인프라 자체는 GitHub의 공용 Runner에서 배포합니다.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout & Setup"
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile

      - name: "Configure AWS Credentials for CDK Deploy"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # "건축가" 역할을 사용하여 인프라를 배포합니다.
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: "Deploy CiCdStack via CDK"
        run: pnpm --filter infra exec cdk deploy CiCdStack --require-approval never